-- PostgreSQL schema for AI Job Intelligence & Career Copilot.
-- Create the configured database first, then run:
-- psql -U postgres -d ai_job_copilot -f database_schema.sql

CREATE TABLE IF NOT EXISTS jobs (
    job_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    company TEXT NOT NULL,
    location TEXT NOT NULL,
    salary TEXT,
    salary_lpa NUMERIC(10, 2),
    description TEXT NOT NULL,
    application_status TEXT NOT NULL DEFAULT 'Not Applied'
        CHECK (application_status IN ('Not Applied', 'Applied', 'Interview', 'Rejected', 'Offer')),
    application_date DATE,
    application_notes TEXT NOT NULL DEFAULT '',
    extracted_skills TEXT[] NOT NULL DEFAULT '{}',
    source TEXT NOT NULL DEFAULT 'local_json',
    source_url TEXT,
    collected_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    job_fingerprint TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS candidate_profiles (
    candidate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    education TEXT,
    experience_years NUMERIC(5, 2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS candidate_skills (
    candidate_id INTEGER NOT NULL REFERENCES candidate_profiles(candidate_id) ON DELETE CASCADE,
    skill TEXT NOT NULL,
    proficiency TEXT,
    PRIMARY KEY (candidate_id, skill)
);

CREATE TABLE IF NOT EXISTS skills (
    skill_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_name TEXT NOT NULL UNIQUE,
    category TEXT
);

CREATE TABLE IF NOT EXISTS job_skills (
    job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
    skill_id INTEGER NOT NULL REFERENCES skills(skill_id) ON DELETE CASCADE,
    importance TEXT NOT NULL DEFAULT 'Required'
        CHECK (importance IN ('Required', 'Preferred')),
    PRIMARY KEY (job_id, skill_id)
);

CREATE TABLE IF NOT EXISTS job_matches (
    candidate_id INTEGER NOT NULL REFERENCES candidate_profiles(candidate_id) ON DELETE CASCADE,
    job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
    required_fit NUMERIC(5, 2) NOT NULL,
    preferred_fit NUMERIC(5, 2) NOT NULL,
    preferred_bonus NUMERIC(5, 2) NOT NULL,
    overall_match NUMERIC(5, 2) NOT NULL,
    match_category TEXT NOT NULL,
    matched_required TEXT[] NOT NULL DEFAULT '{}',
    missing_required TEXT[] NOT NULL DEFAULT '{}',
    matched_preferred TEXT[] NOT NULL DEFAULT '{}',
    missing_preferred TEXT[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (candidate_id, job_id)
);

CREATE TABLE IF NOT EXISTS job_source_metadata (
    job_id INTEGER NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    source_job_id TEXT,
    is_unofficial BOOLEAN,
    posted_at TIMESTAMPTZ,
    posted_days INTEGER,
    industry TEXT,
    role_type TEXT,
    work_type TEXT,
    criteria JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (job_id, source)
);

CREATE INDEX IF NOT EXISTS jobs_search_index ON jobs (location, salary_lpa);
CREATE INDEX IF NOT EXISTS job_matches_candidate_index ON job_matches (candidate_id, overall_match DESC);
